#!/bin/python3
# Jacobus Burger (2022)
# Info:
# Generates a description of a story protagonist randomly.
from random import choice

composure = [
    "sleepy",
    "sad",
    "adventurous",
    "curious",
    "recalcitrant",
    "commanding",
    "cautious",
    "bold",
    "loving",
    "excited",
    "angry",
    "anxious",
    "artistic",
    "bitter",
    "brave",
    "busy",
    "erroneous",
    "friendly",
    "funny",
    "generous",
    "greedy",
    "happy",
    "melancholic",
    "peaceful",
    "quarky",
    "spontaneous",
    "stalward",
    "strange",
    "vitriolic",
    "hyperactive",
    "serendipitous",
    "eccentric",
    "stoic",
    "careful",
    "chaotic",
    "clumsy",
    "talented",
    "georgeous",
    "sneaky",
    "sly",
    "clever",
    "mischevious",
    "mathematical",
    "calculating",
    "quick",
    "angry",
    "beep bop boop",
]

creature = [
    "basilisk",
    "bandersnatch",
    "balrog",   # cool name, not sure what it is
    "bahamut",  # cool name, not sure what it is
    "leviathan",
    "behemoth",
    "bee",
    "bird",
    "nudibranch",
    "android",
    "cyborg",
    "bottle of water",
    "calculus textbook",
    "cat",
    "computer",
    "dragon",
    "elf",
    "eraser with a face drawn on it",
    "flamingo",
    "flea",
    "river",
    "flying tree",
    "gingerbread man",
    "human",
    "leopard",
    "lamp",
    "mountain",
    "planet",
    "quantum soup",
    "snake",
    "the color red",
    "tree",
    "painting",
    "don quixote",
    "horse",
    "fortress",
    "flower",
    "supercomputer",
    "calculator",
    "moth",
    "butterfly",
    "farmer",
    "computer virus",
    "teacup",
    "owl",
    "guitar",
    "trumpet",
    "mutant",
    "monster",
    "phenomenon",
    "void entity",
    "lealani",
]

occupation = [
    "dancer",
    "philosopher",
    "mad scientist",
    "EVA Pilot",
    "astrofreighter",
    "astronaught",
    "astrophysicist",
    "boxer",
    "carpenter",
    "chocolatier",
    "genius",
    "hacker",
    "hole digger",
    "hole filler",
    "librarian",
    "cultist",
    "linguist",
    "mathematician",
    "mecha mechanic",
    "neuromancer",
    "ninja",
    "pen pusher",
    "python programmer",
    "quantum physicist",
    "robot ethicist",
    "roboticist",
    "rubber duck debugger",
    "sewer worker",
    "snake charmer",
    "sniper",
    "spearman",
    "tea enthusiast",
    "time traveler",
    "wizard",
    "bioethicist",
    "geologist",
    "historian",
    "therapist",
    "conman",
    "author",
    "tea farmer",
    "goat milker",
    "hunter",
    "smith",
    "necromancer",
    "magician",
    "bank teller",
    "mechanic",
    "office worker",
    "watcher",
    "musician",
]

strength = [
    "Black Hole",
    "Nuke",
    "Gunpowder Keg",
    "Stick of Dynamite",
    "Mountain",
    "Collosus",
    "Bear",
    "Strongman",
    "Serpent",
    "Fighter",
    "Athlete",
    "Steel Rod",
    "Dry Twig",
    "Rubber Hose",
    "Glass Rod",
]

quest = [
    "a beehive",
    "a bird",
    "a building",
    "a cat",
    "a city",
    "a dark notion",
    "a friendly robot singing \"Hello World\"",
    "a hypothetical connundrum",
    "a logical paradox",
    "a long forgotten language",
    "a planet",
    "a serpent",
    "a time travelling caveman",
    "an ancient dragon",
    "magical sword",
    "monsieur ubu",
    "the collatz conjecture",
    "the cosmos",
    "the essence of lambda calculus",
    "the laundry",
    "the letter 'A'",
    "the light at the end of the tunnel",
    "the number 42",
    "the platonic forms",
    "the towers of hanoi",
    "the m&m secret formula",
    "the world pillars",
    "the name",
    "the ouroboros",
    "oppenheimer",
    "the world",
    "their long lost nickel",
    "their long lost twin",
    "themselves",
    "the mother of computing science",
    "the sun",
    "a serpinsky triangle",
    "reverse polish notation",
    "the consequences of the collatz conjecture",
    "fantastic planet",
]

tool = [
    "stick",
    "rock",
    "master sword",
    "glokenspiel",
    "proton gun",
    "excalibur",
    "Scented Candle",
    "Flashlight",
    "3D printer",
    "magnetron",
    "particle accelerator",
    "drones",
    "nukes",
    "bees",
    "a RPN calculator",
    "group theory",
    "a taylor series",
    "some integrals and derivatives",
    "the fundamental theorem of calculus",
    "dice",
    "a blank canvas",
    "general relativity",
    "the power of hip hop",
    "a rock",
    "category theory",
    "a record player",
    "mitochondria",
    "the power of friendship",
    "the league of super evil",
    "a black hole",
    "string theory",
    "quantum entanglement",
    "a book",
    "the meaning of life",
    "a map",
    "a strange creature",
    "electronic music",
]


def story():
    print(
        "{} {} working as {} and built like {} on a quest to save {} using {}".format(
            choice(composure),
            choice(creature),
            choice(occupation),
            choice(strength),
            choice(quest),
            choice(tool)
        )
    )


if __name__ == '__main__':
    print("type [enter] to generate a description.")
    print("type [q] to quit!")
    while True:
        if input() == "q":
            exit(0)
        story()
